services:
  grafana:
    user: root
    container_name: 'status-panel'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-latest}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    volumes:
      - ./dist:/var/lib/grafana/plugins/status-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/status-panel
      - grafana-plugins:/var/lib/grafana/plugins

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.status-panel:debug
      GF_LOG_LEVEL: info
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: status-panel

volumes:
  grafana-plugins:
