name: Release

on:
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
  PLUGIN_NAME: "status-panel"
  PLUGIN_NAME_SLUG: "benjaminfourmaux-status-panel"

jobs:
  upload_package_on_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "Plugin name $PLUGIN_NAME | version $RELEASE_VERSION"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn -s install

      - name: Build
        run: npm run build

      - name: Sign
        env:
          GRAFANA_ACCESS_POLICY_TOKEN:  ${{ secrets.GRAFANA_SIGN_PLUGIN }}
        run: npx @grafana/sign-plugin@latest
        
      - name: Rename dir
        run: mv ./dist $PLUGIN_NAME_SLUG

      - name: Package Plugin in ZIP
        run: zip -r "$PLUGIN_NAME-$RELEASE_VERSION.zip" $PLUGIN_NAME_SLUG

      - name: Package Plugin in TAR
        run: tar -czvf "$PLUGIN_NAME-$RELEASE_VERSION.tar.gz" $PLUGIN_NAME_SLUG

      - name: Checksum
        run: |
          md5sum $PLUGIN_NAME-$RELEASE_VERSION.zip
          md5sum $PLUGIN_NAME-$RELEASE_VERSION.tar.gz

      - name: Upload asset to release
        uses: csexton/release-asset-action@v3
        with:
          files: |
            ${{ env.PLUGIN_NAME }}-${{ env.RELEASE_VERSION }}.zip
            ${{ env.PLUGIN_NAME }}-${{ env.RELEASE_VERSION }}.tar.gz
          github-token: ${{ secrets.GITHUB_TOKEN }}
