name: Test-e2e

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main

jobs:
  build_and_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js env
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn -s install

      # Linter steps
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint

      # Build
      - name: Build
        run: yarn build

      # Install playwright
      - name: Install Playwright Browsers
        run: yarn -s playwright install --with-deps

      # Start Grafana container
      - name: Start Grafana
        run: |
          docker compose pull
          docker compose up -d

      - name: Wait for grafana server
        uses: grafana/plugin-actions/wait-for-grafana@main

      # Run playwright Tests
      - name: Run Playwright tests
        id: run-tests
        run: yarn playwright test


