name: Plugin-Validator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - mainr

jobs:
  plugin-validator:
    name: Grafana Plugin Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "Branch name: $GITHUB_REF"

      - name: Build Package
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn -s install
      - run: npm run build

      - name: Remove dir
        run: mv ./dist status-panel
      
      # Archive the builded plugin into Zip
      - name: Package Plugin
        run: zip -r plugin.zip status-panel
        
      - name: Run Validator
        uses: tj-actions/docker-run@v2.2.1
        with:
          image: grafana/plugin-validator-cli:latest
          name: validator
          options: -v ${{github.workspace}}/plugin.zip:/plugin.zip -v ${{github.workspace}}/.config/plugin-validator.yaml:/config.yaml
          args: -config /config.yaml -sourceCodeUri "https://github.com/BenjaminFourmaux/Grafana_Status_panel/tree/test-e2e" /plugin.zip
